import type { Educator } from "@/lib/types";

type EducatorSpec = Omit<Educator, "id" | "firstName" | "courseIds"> & { courses: string[] };

/** Fictional educators for the demo catalog. */
export const educatorSpecs: EducatorSpec[] = [
  {
    handle: "sarah-chen",
    name: "Sarah Chen",
    headline: "Calculus teacher who makes the notation disappear",
    bio: "I taught AP Calculus BC for nine years at a public magnet school in Oakland, and 94% of my students passed. I explain every idea twice: once as a picture, once as algebra. Most students who struggle with calculus are really struggling with the notation, and that part is fixable.",
    subjects: ["Calculus", "Precalculus", "SAT Math"],
    courses: ["ap-calculus-bc", "sat-math"],
    credentials: ["M.A. Mathematics Education, UC Berkeley", "AP Reader, Calculus (6 years)"],
    rating: 4.97,
    ratingCount: 312,
    hourlyRate: 85,
    yearsTeaching: 11,
    location: "Oakland, CA",
    responseTime: "Usually replies within a few hours",
    acceptingStudents: true,
    bookingUrl: null,
    hue: 232,
  },
  {
    handle: "marcus-okafor",
    name: "Marcus Okafor",
    headline: "Former engineer, worked-examples specialist",
    bio: "I spent six years as a structural engineer before I started teaching. My lessons are built on worked examples: I solve the problem in front of you, say out loud every decision I make, then you try the next one.",
    subjects: ["Calculus", "Physics", "SAT Math"],
    courses: ["ap-calculus-bc", "sat-math"],
    credentials: ["B.S. Civil Engineering, Georgia Tech", "Teaching since 2017"],
    rating: 4.91,
    ratingCount: 204,
    hourlyRate: 70,
    yearsTeaching: 8,
    location: "Atlanta, GA",
    responseTime: "Usually replies within a day",
    acceptingStudents: true,
    bookingUrl: null,
    hue: 20,
  },
  {
    handle: "priya-raman",
    name: "Priya Raman",
    headline: "Series and proofs, taught calmly",
    bio: "I'm finishing a math PhD, and I tutor because I like watching the moment when a proof finally makes sense. Series is my favorite unit to teach because it's the one students fear most, and it doesn't need to be.",
    subjects: ["Calculus", "Real Analysis"],
    courses: ["ap-calculus-bc"],
    credentials: ["Ph.D. candidate, Mathematics, University of Michigan"],
    rating: 4.95,
    ratingCount: 128,
    hourlyRate: 90,
    yearsTeaching: 6,
    location: "Ann Arbor, MI",
    responseTime: "Usually replies within a day",
    acceptingStudents: true,
    bookingUrl: null,
    hue: 280,
  },
  {
    handle: "daniel-reyes",
    name: "Daniel Reyes",
    headline: "AP World teacher. Big picture first, then evidence.",
    bio: "I've taught AP World History for twelve years in Houston and have read DBQs at the AP Reading for five of them. I teach history as arguments about causation and change, because that's how the exam grades it.",
    subjects: ["World History", "US History"],
    courses: ["ap-world-history"],
    credentials: ["AP Reader, World History (5 years)", "M.Ed., University of Houston"],
    rating: 4.96,
    ratingCount: 276,
    hourlyRate: 75,
    yearsTeaching: 12,
    location: "Houston, TX",
    responseTime: "Usually replies within a few hours",
    acceptingStudents: true,
    bookingUrl: null,
    hue: 28,
  },
  {
    handle: "amara-bello",
    name: "Amara Bello",
    headline: "Historian of trade networks and empire",
    bio: "My research is on Indian Ocean commerce, so I think about the past as a set of connections. My videos are short on purpose: one idea, three pieces of evidence, and how to use them in an essay.",
    subjects: ["World History", "African History"],
    courses: ["ap-world-history"],
    credentials: ["Ph.D. History, Northwestern", "Former AP World teacher"],
    rating: 4.93,
    ratingCount: 141,
    hourlyRate: 80,
    yearsTeaching: 9,
    location: "Chicago, IL",
    responseTime: "Usually replies within a day",
    acceptingStudents: true,
    bookingUrl: null,
    hue: 12,
  },
  {
    handle: "tom-lindqvist",
    name: "Tom Lindqvist",
    headline: "Timelines, maps, and the reasoning behind them",
    bio: "I'm a high school history teacher who draws everything. If you're a visual learner, my maps and timelines are made for you.",
    subjects: ["World History", "European History"],
    courses: ["ap-world-history"],
    credentials: ["M.A. History, University of Minnesota"],
    rating: 4.84,
    ratingCount: 97,
    hourlyRate: 60,
    yearsTeaching: 7,
    location: "Minneapolis, MN",
    responseTime: "Usually replies within 2 days",
    acceptingStudents: false,
    bookingUrl: null,
    hue: 200,
  },
  {
    handle: "jordan-kim",
    name: "Jordan Kim",
    headline: "SAT strategist, 1580 → full-time tutor",
    bio: "I've tutored the SAT full time for seven years and taken the digital version four times. I teach the fastest reliable method for each question type, including when to hand the problem to Desmos.",
    subjects: ["SAT Math", "SAT Reading & Writing"],
    courses: ["sat-math", "sat-reading-writing"],
    credentials: ["1580 SAT", "B.A. Economics, UCLA", "2,000+ hours tutoring"],
    rating: 4.94,
    ratingCount: 389,
    hourlyRate: 95,
    yearsTeaching: 7,
    location: "Los Angeles, CA",
    responseTime: "Usually replies within a few hours",
    acceptingStudents: true,
    bookingUrl: null,
    hue: 160,
  },
  {
    handle: "elena-vasquez",
    name: "Elena Vasquez",
    headline: "Grammar without the jargon",
    bio: "I taught high school English for ten years and I edit for a living now. The SAT tests the same small set of rules again and again, and I'll show you how to hear them.",
    subjects: ["SAT Reading & Writing", "English"],
    courses: ["sat-reading-writing"],
    credentials: ["M.A. English, UT Austin", "Former department head"],
    rating: 4.92,
    ratingCount: 173,
    hourlyRate: 65,
    yearsTeaching: 10,
    location: "Austin, TX",
    responseTime: "Usually replies within a day",
    acceptingStudents: true,
    bookingUrl: null,
    hue: 330,
  },
  {
    handle: "nia-thompson",
    name: "Nia Thompson",
    headline: "Biology through experiments you can picture",
    bio: "I was a molecular biology researcher and now teach AP Bio in Baltimore. I explain processes as stories, with molecules as characters and clear causes and effects, because that's how the free-response questions are written.",
    subjects: ["Biology", "Biochemistry"],
    courses: ["ap-biology"],
    credentials: ["M.S. Molecular Biology, Johns Hopkins", "AP Biology teacher"],
    rating: 4.95,
    ratingCount: 158,
    hourlyRate: 70,
    yearsTeaching: 8,
    location: "Baltimore, MD",
    responseTime: "Usually replies within a day",
    acceptingStudents: true,
    bookingUrl: null,
    hue: 140,
  },
  {
    handle: "sam-patel",
    name: "Sam Patel",
    headline: "Pre-med who tutors bio and chem on the side",
    bio: "I got 5s in AP Bio and AP Chem three years ago, so I remember what was actually confusing. My videos are fast and practical, and they cover the questions my students ask most.",
    subjects: ["Biology", "Chemistry"],
    courses: ["ap-biology", "ap-chemistry"],
    credentials: ["B.S. Biochemistry (in progress), Duke"],
    rating: 4.81,
    ratingCount: 64,
    hourlyRate: 45,
    yearsTeaching: 3,
    location: "Durham, NC",
    responseTime: "Usually replies within a few hours",
    acceptingStudents: true,
    bookingUrl: null,
    hue: 48,
  },
  {
    handle: "hannah-weiss",
    name: "Hannah Weiss",
    headline: "Chemistry is Coulomb's law, over and over",
    bio: "I taught chemistry for fourteen years before moving to curriculum design. Almost every AP Chem explanation comes back to charge and distance, and once you see that, the whole course gets smaller.",
    subjects: ["Chemistry", "Physics"],
    courses: ["ap-chemistry"],
    credentials: ["M.S. Chemistry, University of Wisconsin", "National Board Certified"],
    rating: 4.98,
    ratingCount: 221,
    hourlyRate: 80,
    yearsTeaching: 14,
    location: "Madison, WI",
    responseTime: "Usually replies within a day",
    acceptingStudents: true,
    bookingUrl: null,
    hue: 196,
  },
];
