/**
 * Generates supabase/seed.sql from the catalog in src/lib/catalog.
 *   npm run db:seed
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { buildCatalog } from "../src/lib/catalog/build";

const q = (v: string | null | undefined) => (v == null ? "null" : `'${v.replace(/'/g, "''")}'`);
const arr = (xs: string[]) => (xs.length ? `array[${xs.map(q).join(", ")}]::text[]` : "'{}'::text[]");
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

function insert(table: string, cols: string[], rows: string[][]) {
  if (!rows.length) return "";
  const values = rows.map((r) => `  (${r.join(", ")})`).join(",\n");
  return `insert into public.${table} (${cols.join(", ")}) values\n${values}\non conflict (id) do nothing;\n\n`;
}

const c = buildCatalog();
let sql = "-- Generated by scripts/generate-seed.ts. Do not edit by hand.\n\n";

sql += insert(
  "courses",
  ["id", "slug", "title", "short_title", "exam", "subject", "description", "hue", "exam_month", "position"],
  c.courses.map((x, i) => [q(x.id), q(x.slug), q(x.title), q(x.shortTitle), q(x.exam), q(x.subject), q(x.description), String(x.hue), q(x.examMonth), String(i)]),
);
sql += insert(
  "units",
  ["id", "course_id", "slug", "title", "summary", "position"],
  c.units.map((x) => [q(x.id), q(x.courseId), q(x.slug), q(x.title), q(x.summary), String(x.order)]),
);
sql += insert(
  "concepts",
  ["id", "unit_id", "course_id", "slug", "title", "position"],
  c.concepts.map((x) => [q(x.id), q(x.unitId), q(x.courseId), q(x.slug), q(x.title), String(x.order)]),
);
sql += insert(
  "topics",
  ["id", "concept_id", "unit_id", "course_id", "slug", "title", "summary", "glyph", "key_points", "aliases", "position"],
  c.topics.map((x) => [q(x.id), q(x.conceptId), q(x.unitId), q(x.courseId), q(x.slug), q(x.title), q(x.summary), q(x.glyph), arr(x.keyPoints), arr(x.aliases), String(x.order)]),
);
sql += insert(
  "educators",
  ["id", "handle", "name", "headline", "bio", "subjects", "course_ids", "credentials", "rating", "rating_count", "hourly_rate", "years_teaching", "location", "response_time", "accepting_students", "booking_url", "hue"],
  c.educators.map((x) => [q(x.id), q(x.handle), q(x.name), q(x.headline), q(x.bio), arr(x.subjects), arr(x.courseIds), arr(x.credentials), String(x.rating), String(x.ratingCount), String(x.hourlyRate), String(x.yearsTeaching), q(x.location), q(x.responseTime), String(x.acceptingStudents), q(x.bookingUrl), String(x.hue)]),
);
sql += insert(
  "videos",
  ["id", "topic_id", "educator_id", "title", "description", "style", "duration_sec", "published_at", "chapters", "media_url", "status", "base_views", "base_completions", "base_avg_watch_fraction", "base_helpful", "base_not_helpful", "base_saves", "base_rewatch_rate", "base_early_drop_rate"],
  c.videos.map((x) => [q(x.id), q(x.topicId), q(x.educatorId), q(x.title), q(x.description), q(x.style), String(x.durationSec), q(x.publishedAt), json(x.chapters), q(x.mediaUrl), q(x.status), String(x.stats.views), String(x.stats.completions), String(x.stats.avgWatchFraction), String(x.stats.helpful), String(x.stats.notHelpful), String(x.stats.saves), String(x.stats.rewatchRate), String(x.stats.earlyDropRate)]),
);

const out = path.join(process.cwd(), "supabase", "seed.sql");
writeFileSync(out, sql);
console.log(`Wrote ${out}: ${c.courses.length} courses, ${c.topics.length} topics, ${c.educators.length} educators, ${c.videos.length} videos.`);
